# ExceptionLib
Simple Package for manage responses and exceptions

## Using returns:

1. **Successful** (return an Successful object): 
  ```csharp
    return ExceptionLib.Response.Successful(new { id = user.Id, services = accessesTokenUser });
  ```
  
2. **WithException:**
 ```csharp
  catch(Exception ex)
  {
      return ExceptionLib.Response.WithErrorException(ex);
  }
```

## Getting returns:

**Format response:**
```csharp
{
"response": boolean,
"successful": boolean,
"data": object,
"message": string,
"error": string
}
```

If you want receive the response generated by ExceptionLib, this is the way:
 ```csharp
var resultDTO = new ExceptionLib.ResultDto(result);
Console.WritLine(resultDTO.error);
```
            
    
